# Setup and configure our environment as a RHEL based
# microshift environment
#
# Execution
#  ansible-playbook  -i ./hosts ./microshift.yaml
# 
# Requires
#  secrets.yaml with Red Hat Activation Key
#
---
- hosts: microshift
  become: True
  become_user: root
  vars_files:
    #- ./vars/common.yml
    #- ./vars/{{ redpill_region }}.yaml
    - ./secrets.yaml
  tasks:

  - name: Copy ssh-id (public key) to MicroShift image to enable authenticationb // ssh-copy-id -i ~/.ssh/id_rsa.pub redhat@192.168.122.91
    ansible.posix.authorized_key:
      user: redhat
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  
 

  - name: Enable Red Hat Subscription if we're on RHEL
    include_role: name=register-rhel-subscription
    when: 
      - rh_org_activationkey is defined
      - ansible_facts['distribution'] == "RedHat"

  - name: Enable all repositories required for microshift
    community.general.rhsm_repository:
      name: "{{item}}"
      state: enabled
    with_items:
     - 'rhocp-4.13-for-rhel-9-x86_64-rpms'
     - 'fast-datapath-for-rhel-9-x86_64-rpms'

  - name: Install the microshif dependencies
    yum:
      name: ['microshift', 'microshift-greenboot' ]
      state: present

  - name: Enable Firewalld
    systemd:
      name: firewalld
      state: started
      enabled: yes
      masked: no

  - name: Firewalld rules for our microshift zones
    firewalld:
      zone: "trusted"
      source: "{{item}}"
      immediate: true
      permanent: true
      state: enabled
    with_items:
     - '10.42.0.0/16'
     - '169.254.169.1'

  - name: Allow external access to the microshift API on 6443
    firewalld:
      zone: "public"
      port: "6443/tcp"
      immediate: true
      permanent: true
      state: enabled

  - name: Copy our OpenShift Pull secret
    copy:
      src: openshift-pull-secret
      dest: /etc/crio/openshift-pull-secret
      owner: root
      group: root
      mode: 0600

  - name: Start & enable microshift
    ansible.builtin.service:
      name: microshift.service
      enabled: true
      state: started

  - name: create directory for kubeconfig
    file: 
      path: /home/redhat/.kube
      state: directory

  - name: Create kubeconfig in /home/redhat/.kube/config
    ansible.builtin.shell: sudo cat /var/lib/microshift/resources/kubeadmin/kubeconfig > /home/redhat/.kube/config