apiVersion: v1
kind: ServiceAccount
metadata:
  name: apriltag
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: apriltag
  labels:
    app: apriltag
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apriltag
      version: v1
  template:
    metadata:
      labels:
        app: apriltag
        version: v1
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1000Mi
            requests:
              cpu: '.5'
              memory: 800Mi
          terminationMessagePath: /dev/termination-log
          name: apriltag
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          ports:
            - name: apriltag
              containerPort: 6000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: quay.io/andyyuen/apriltag-detect:1.0
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: apriltag
      serviceAccount: apriltag
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: apriltag
  labels:
    app: apriltag
    service: apriltag
spec:
  type: NodePort
  ports:
    - name: apriltag
      protocol: TCP
      port: 6000
      nodePort: 30600
  sessionAffinity: None
  selector:
    app: apriltag

