apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-server
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: edge-server
  labels:
    app: edge-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-server
      version: v1
  template:
    metadata:
      labels:
        app: edge-server
        version: v1
    spec:
      containers:
        - resources:
            limits:
              cpu: '1.5'
              memory: 1500Mi
            requests:
              cpu: '.5'
              memory: 800Mi
          terminationMessagePath: /dev/termination-log
          name: edge-server
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          ports:
            - name: edge-server
              containerPort: 5005
              protocol: TCP
          envFrom:
          - configMapRef:
              name: config
          volumeMounts:
            - name: config
              mountPath: /app/config
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: quay.io/andyyuen/edge-server:1.0
      volumes:
        - name: config
          configMap:
            name: config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: edge-server
      serviceAccount: edge-server
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: edge-server
  labels:
    app: edge-server
    service: edge-server
spec:
  type: NodePort
  ports:
    - name: edge-server
      protocol: TCP
      port: 5005
      nodePort: 30505
  sessionAffinity: None
  selector:
    app: edge-server

