apiVersion: v1
kind: ServiceAccount
metadata:
  name: robots
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: robots
  labels:
    app: robots
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robots
      version: v1
  template:
    metadata:
      labels:
        app: robots
        version: v1
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1000Mi
            requests:
              cpu: '.5'
              memory: 800Mi
          terminationMessagePath: /dev/termination-log
          name: robots
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          ports:
            - name: robots
              containerPort: 5000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: quay.io/andyyuen/robots:1.0
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: robots
      serviceAccount: robots
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: robots
  labels:
    app: robots
    service: robots
spec:
  type: NodePort
  ports:
    - name: robots
      protocol: TCP
      port: 5000
      nodePort: 30500
  sessionAffinity: None
  selector:
    app: robots

