apiVersion: v1
kind: ServiceAccount
metadata:
  name: rtsp
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rtsp
  labels:
    app: rtsp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp
      version: v1
  template:
    metadata:
      labels:
        app: rtsp
        version: v1
    spec:
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 1500Mi
            requests:
              cpu: '1'
              memory: 800Mi
          terminationMessagePath: /dev/termination-log
          name: rtsp
          env:
            - name: RTSP_PROTOCOLS
              value: "tcp"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          ports:
            - name: rtsp
              containerPort: 8554
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: docker.io/aler9/rtsp-simple-server:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: rtsp
      serviceAccount: rtsp
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: rtsp
  labels:
    app: rtsp
    service: rtsp
spec:
  type: NodePort
  ports:
    - name: rtsp
      protocol: TCP
      port: 8554
      nodePort: 30854
  sessionAffinity: None
  selector:
    app: rtsp
    
