---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: model-pipeline
  namespace: edge-robotics
spec:
  params:
    - name: QUAY_USER
      type: string
      description: The quay.io username the image will be pushed to.
      default: tcorcoran
    - name: MODEL_REPOSITORY
      type: string
      description: The git respository clone url containing model content.
      default: https://github.com/tnscorcoran/GuiseAI-Openshift
  tasks:
    - name: git-clone
      params:
        - name: url
          value: "$(params.MODEL_REPOSITORY)"
        - name: revision
          value: ""
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: Model Workspace
    - name: buildah
      params:
        - name: IMAGE
          value: "quay.io/$(params.QUAY_USER)/guise-model"
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: Model Workspace
  workspaces:
    - name: Model Workspace
